version: '3.3'

services:
  portainer-agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - /var/lib/docker/volumes:/var/lib/docker/volumes  

  nginx:
    image: 192.168.254.100:5000/nginx-nikitin 
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/logs:/var/log/nginx  
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
